server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-cn-jte3sc7m40008aqo.rwlb.rds.aliyuncs.com:3306/im_center?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true&connectionCollation=utf8mb4_unicode_ci
    username: storm
    password: Lzy303051@
    type: com.alibaba.druid.pool.DruidDataSource
  mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  mq:
    rabbit:
      client:
        default:
          host: 127.0.0.1
          port: 5672
          username: guest
          password: guest
          virtualHost: /
          #          supportDelayed: true
          codecId: JSON
          connection:
            connectionTimeout: 3000
            maxConnection: 10
            minIdle: 10
            minIdleTime: 30000
            readBufferSize: 1048576
            writeBufferSize: 1048576
          ioThread:
            threadCount: 10
            queueSize: -1
            threadName: rabbitmq-io-thread
          producerThread:
            threadCount: 10
            queueSize: -1
            threadName: rabbitmq-producer-thread
          consumerThread:
            threadCount: 10
            queueSize: -1
            threadName: rabbitmq-consumer-thread
          publisher:
            exchange:
              name: storm-cloud
          consumer:
            exchange:
              name: storm-cloud
            channel:
              basicQos: 100
            queue:
              durable: true
              maxLength: 1000000
              maxLengthBytes: 1073741824